### ISSUE TITLE
Error detecting the version of libcrypto

### ISSUE THREAD

**Issue by Kahvi-0** [mpgn/CrackMapExec#108]
Some features have reported "Error detecting the version of libcrypto".

Steps to reproduce the behavior i.e.:
*With the latest pull from master at time of writing*
Command: `cme ldap [] -u '' -p '' -M ldap-checker`
Resulted in:
```
[-] Failed loading module at /home/kali/.local/lib/python3.11/site-packages/cme/modules/ldap-checker.py: Error detecting the version of libcrypto
Traceback (most recent call last):
  File "/home/kali/.local/bin/cme", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/cme/crackmapexec.py", line 179, in main
    modules = loader.list_modules()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/cme/loaders/moduleloader.py", line 136, in list_modules
    modules.update(module_data)
TypeError: 'NoneType' object is not iterable
```

Similar behavior if the RDP protocol is used

Command: `cme rdp [] -u '' -p ''`
```
Traceback (most recent call last):
  File "/home/kali/.local/bin/cme", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/cme/crackmapexec.py", line 162, in main
    protocol_object = getattr(p_loader.load_protocol(protocol_path), args.protocol)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.local/lib/python3.11/site-packages/cme/loaders/protocolloader.py", line 18, in load_protocol
    loader.exec_module(protocol)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/.local/lib/python3.11/site-packages/cme/protocols/rdp.py", line 17, in <module>
    from aardwolf.connection import RDPConnection
  File "/home/kali/.local/lib/python3.11/site-packages/aardwolf/connection.py", line 16, in <module>
    from asyauth.common.credentials import UniCredential
  File "/home/kali/.local/lib/python3.11/site-packages/asyauth/common/credentials/__init__.py", line 315, in <module>
    from asyauth.common.credentials.kerberos import KerberosCredential
  File "/home/kali/.local/lib/python3.11/site-packages/asyauth/common/credentials/kerberos.py", line 7, in <module>
    from minikerberos.common.creds import KerberosCredential as KCRED
  File "/home/kali/.local/lib/python3.11/site-packages/minikerberos/common/creds.py", line 21, in <module>
    from oscrypto.asymmetric import rsa_pkcs1v15_sign, load_private_key
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/home/kali/.local/lib/python3.11/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

```

Typically protocols such as RDP and modules such as ldap-checker ran as expected. 

 - OS: Linux kali 6.1.0-kali9-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
 - Version of CME: 6.0.1 (pulled from master at time of writing)
 - Installed from: https://github.com/mpgn/CrackMapExec using python method

**Comment by mpgn** [comment]
Hello, i cannot reproduce, it's more a problem on your setup than cme for me

**Comment by Kahvi-0** [comment]
Hello. A few peers also seemed to have a similar issues have updating their Kali yesterday. Thought maybe there was a conflict somewhere.

Fresh new Kali VM before updates: Linux kali 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
Install method: python

![image](https://github.com/mpgn/CrackMapExec/assets/46513413/70cfa128-304c-4b58-b558-0663e1080ebe)


Same Kali after running: apt update / upgrade
![image](https://github.com/mpgn/CrackMapExec/assets/46513413/c361523c-562d-47c3-aed2-a524eea2c802)

**Comment by carter-twi** [comment]
Seeing the same result here on a fresh Kali/cme install.

**Comment by NeffIsBack** [comment]
Is this only a problem with rdp and ldap? Can you give me the debug output of these commands with ˋcme --debug ...ˋ?

**Comment by NeffIsBack** [comment]
Can you check if smb with Kerberos is working?

**Comment by NeffIsBack** [comment]
This looks to me like a problem in minikerberos with some packages messing up its dependencies. I will take a look at it tomorrow.
In the meantime you could try to ’poetry add libcrypto’ and see if that temporarily solves the issue

**Comment by Kahvi-0** [comment]
It seems like the error preventing the ldap-checker module is also affecting loading any other modules from being loaded. 

LDAP protocol with module map
![image](https://github.com/mpgn/CrackMapExec/assets/46513413/c8c02a24-73cc-4ee5-9290-70b3f8d6fd8d)

SMB protocol with module enum_av
![image](https://github.com/mpgn/CrackMapExec/assets/46513413/e4807ce3-c359-4d3f-a88e-f8291fe9c0ec)

**Comment by NeffIsBack** [comment]
You installed cme using poetry right? Please do a `poetry install` and then run it with `poetry run cme`.

**Comment by QU35T-code** [comment]
It looks like you must have python dependencies that don't work with cme. The module is well functional on Exegol. Try using cme in a python venv :)

<img width="1686" alt="image" src="https://github.com/mpgn/CrackMapExec/assets/51704860/593a68f3-d1c1-4eff-a434-ce635325f351">

**Comment by NeffIsBack** [comment]
Exactly. To give a more precise answer as my first one, you are executing the poetry binary file from cme directly and therefore it uses the system installation from python. Therefore probably a lot of packages are missing.
To use poetry properly `poetry run cme` will execute the binary using the venv that poetry created with `poetry install`.

Although poetry is nice for managing dependencies i would recommend using pipx to install cme, as this will make cme system-wide available. You can install cme with pipx directly from github (this will allow you to also update directly from github):
`pipx install git+https://github.com/mpgn/CrackMapExec`

**Comment by Kahvi-0** [comment]
Just to confirm from earlier I did use pipx to install. Personally my preferred method as well. IIRC poetry was fine for me as long as you didn't update kali while trying to do the poetry install. 

![image](https://github.com/mpgn/CrackMapExec/assets/46513413/40aa7065-6ad6-486e-a78c-72554c88bba9)

**Comment by Kahvi-0** [comment]
Was able to now pull the version for the 110 pull req linked above and it no longer fails to load other modules when failing to load the ldap-checker module :)

**Comment by mpgn** [comment]
At least, that's something :)

**Comment by NeffIsBack** [comment]
> Just to confirm from earlier I did use pipx to install. Personally my preferred method as well. IIRC poetry was fine for me as long as you didn't update kali while trying to do the poetry install.

Hmm okay sorry i guess i was wrong about the venv. My best guess is that it has still something to do with asyauth

**Comment by carter-twi** [comment]
To add on - I also did a fresh install of kali and then installed cme with pipx. RDP still seems to be having issues. Happy to provide anything else I can. 
![Screenshot 2023-08-18 095130](https://github.com/mpgn/CrackMapExec/assets/131391884/24b145c2-66a9-4b29-8be6-46d8c7363644)

**Comment by NeffIsBack** [comment]
I could reproduce this error with the latest kali vm build.

Two days ago on 16.08.23 openssl 3.0.10-1 was released added to the kali repositorys: https://pkg.kali.org/pkg/openssl
This apperently broke the regex which was used to detect openssl in the oscrypto package. 
Therefore the oscrypto package broke, so did the asyauth library from skelsec and with it some of cme's modules.

They already pushed a commit to fix the regex in oscrypto which works on my installation.
To make a dirty fix you can do the following:
1. Add `oscrypto = { git = "https://github.com/wbond/oscrypto" }` to the dependency section of the pyproject.toml file
2. Run `poetry lock --no-update`
3. Run `poetry install`

In the mean time i will ask if they can release a new version to pypi with the bugfix

**Comment by mpgn** [comment]
crazy ! good catch 💪

**Comment by Kahvi-0** [comment]
An alt method to this that seemed to work for me but for python install (either directly to system or pyenv) was this:

1. git clone https://github.com/wbond/oscrypto.git
2. cd oscrypto
3. pip3 install .
