### ISSUE TITLE
Syntax Error when running the CME binary

### ISSUE THREAD

**Issue by init5-SF** [mpgn/CrackMapExec#12]
**Describe the bug**
I downloaded the latest linux version from https://github.com/mpgn/CrackMapExec/releases/download/v6.0.0/cme-ubuntu-latest-3.11.zip
did a chmod +x then tried running the tool, that's when it gave me the below error

**To Reproduce**
Command: `./cme -h`
Resulted in:
```
└─# ./cme -h                                                                                                                                                                              1 ⨯
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./cme/__main__.py", line 2, in <module>
  File "./cme/_bootstrap/__init__.py", line 107
    return root / f"{name}_{build_id}"
                                     ^
SyntaxError: invalid syntax
```

**Expected behavior**
The help menu and the banner should be printed on the screen

**Screenshots**
![Screenshot 2023-06-30 224530](https://github.com/mpgn/CrackMapExec/assets/10214861/1c112b48-5f75-45de-ab1b-0f20e20f6124)

**Crackmapexec info**
 - OS: Kali
 - Version of CME: 6.0.0
 - Installed from: Downloaded the binary from releases page
- Installed Python versions:

![image](https://github.com/mpgn/CrackMapExec/assets/10214861/a142bc2a-aeaf-42da-899e-383dc06b2b0c)

**Comment by NeffIsBack** [comment]
Please make sure you are executing cme with python3. Python 2 is not supported.

This could help you setting python3 as default: https://stackoverflow.com/questions/61030194/change-the-default-version-of-python-in-kali-linux

**Comment by init5-SF** [comment]
Hello @NeffIsBack 

Thanks for the info, I have configured Python3.11 to be the default python version on my Kali, now when I try to run cme I get a different error.

please check the screenshot:
![Screenshot 2023-07-02 193641](https://github.com/mpgn/CrackMapExec/assets/10214861/3f976d67-8b9e-48e5-a9c8-097b6c699df0)


Any ideas?

**Comment by NeffIsBack** [comment]
This is really weird. I will take a look into it. Can you try to install cme with pipx in the meantime?

`sudo apt install python3-pipx git`
`pipx install git+https://github.com/mpgn/CrackMapExec`

**Comment by init5-SF** [comment]
Sure, will give it a try.
Do I need to uninstall the currently installed cme first? (I have an older version 5.4.0 installed via apt)

**Comment by NeffIsBack** [comment]
Can you give me your pip version?
Did you install pipx with apt or pip?

For the binary an dirty fix would be to simply `pip install python-libnmap`.
For pipx you could try to to uninstall pipx, remove the local folder `rm -rf ~/.local/pipx/` and reinstall it with `sudo apt install pipx`.

I will try to recreate the problem in the meantime

**Comment by mpgn** [comment]
Hello @init5-SF i've updated to binairies, can you test with this one https://github.com/mpgn/CrackMapExec/suites/14024895661/artifacts/783055822 ?

https://github.com/mpgn/CrackMapExec/actions/runs/5444142064

**Comment by init5-SF** [comment]
Hello @mpgn 
This binary version works!! Thank you so much!😊

btw are you going to update the cme version in the Kali repo or this is no longer supported?

**Comment by mpgn** [comment]
it is, i'm wating for more issue before the update on kali, because once the new version is shipped it take times to update so better send a clean version :)
