### ISSUE TITLE
RDP spray does not finish....

### ISSUE THREAD

**Issue by adamast0r** [mpgn/CrackMapExec#122]
**Describe the bug**
RDP scan does not finish

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `cme rdp hosts_external.txt -u users.txt -p 'Password1' -d test.example  --continue-on-success `
Resulted in:
```
RDP         192.168.210.145 3389   TEST             [*] Windows 10 or Windows Server 2016 Build 19041 (name:TEST) (domain:test.example) (nla:True)
RDP         192.168.210.145 3389   TEST             [-] test.example\Administrator:Password1 (STATUS_LOGON_FAILURE)
RDP         192.168.210.145 3389   TEST             [-] test.example\carlo:Password1 (STATUS_LOGON_FAILURE)
RDP         192.168.210.145 3389   TEST             [-] test.example\chloe:Password1 (STATUS_LOGON_FAILURE)
RDP         192.168.210.145 3389   TEST             [-] test.example\stuart:Password1 (STATUS_LOGON_FAILURE)
RDP         192.168.210.145 3389   TEST             [-] test.example\aman:Password1 (STATUS_LOGON_FAILURE)
Running CME against 4 targets ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━  75% 0:00:01
...
```

**Expected behavior**
The scan should finish, it keeps running...The scan has the following hosts:

cat hosts_external.txt 
192.168.210.141
192.168.210.143
192.168.210.144
192.168.210.145

**Crackmapexec info**
 - OS: kali 
 - Version : 6.0.1 - Bane

**Comment by XiaoliChan** [comment]
Can you try the master branch? This issues should be already fixed in master branch not release branch

**Comment by XiaoliChan** [comment]
@adamast0r ping

**Comment by adamast0r** [comment]
@XiaoliChan it is indeed fixed in the last version, it can be closed thanks! When is this going to be in a "normal" release?

**Comment by NeffIsBack** [comment]
> @XiaoliChan it is indeed fixed in the last version, it can be closed thanks! When is this going to be in a "normal" release? 

We will release a version soon :)
