### ISSUE TITLE
Error connecting to the domain, are you sure LDAP service is running on the target?

### ISSUE THREAD

**Issue by PierreFReims** [mpgn/CrackMapExec#124]
**Describe the bug**
I am trying to query ldap on a Domain Controller, but CME tells me that apparently, the service is not running on the target.

Howerver, the service is properly running:
![image](https://github.com/mpgn/CrackMapExec/assets/46540237/1cb0740f-3394-4200-9eef-86e21344dc8b)

**To Reproduce**
Command: `poetry run crackmapexec ldap 192.168.42.20 -u 'user' -p ''`

Resulted in:
```
SMB         192.168.42.20   445    DC1              [*] Windows 10.0 Build 17763 x64 (name:DC1) (domain:redteamlab.local) (signing:True) (SMBv1:False)
LDAP        192.168.42.20   445    DC1              [-] redteamlab.local\alice: Error connecting to the domain, are you sure LDAP service is running on the target?
Error: [Errno Connection error (DC1.redteamlab.local:389)] [Errno -2] Name or service not known
```

**Expected behavior**
I want to query the ldap service and work with all available commands

**Screenshots**
![image](https://github.com/mpgn/CrackMapExec/assets/46540237/437da5e3-f0b6-43e3-8ba5-d1de1e2f269c)

**Crackmapexec info**
 - OS: kali
 - Version of CME: 6.0.1 - Bane
 - Installed from: GitHub repository

**Additional information**
 - Windows firewall allow inbound connections on TCP and UDP 389
 - I tried to run the command with `-k` tag
 when I used `-k`, the initial 'Error connecting to the domain, are you sure LDAP service is running on the target?' disappear, but I still have the 'Name or service not known' error

**Comment by XiaoliChan** [comment]
Please add
`192.168.42.20 redteamlab.local` into your `/etc/hosts` file

**Comment by PierreFReims** [comment]
I am getting the same issue

![image](https://github.com/mpgn/CrackMapExec/assets/46540237/7da5285a-f2ae-4b54-a922-99a0dffc030a)

**Comment by XiaoliChan** [comment]
Okay, you are missing `192.168.42.20 redteamlab.local dc1 dc1.redteamlab.local`

the `dc1` and `dc1.redteamlab.local`

**Comment by PierreFReims** [comment]
Thank you, why didn't I think to this ...
![image](https://github.com/mpgn/CrackMapExec/assets/46540237/6bf1c737-c48e-468e-812a-4075b8aae975)

**Comment by XiaoliChan** [comment]
> Thank you, why didn't I think to this ... ![image](https://user-images.githubusercontent.com/46540237/263221657-6bf1c737-c48e-468e-812a-4075b8aae975.png)

Because in `CME`, default is using `target ip` as `kdchost`, but you given `ip address`, so that will unable authenticate into AD, you can try with this

`crackmapexec ldap dc1.redteamlab.local -u alice -p Password1`

**Comment by PierreFReims** [comment]
I understand the mecanism. All good. Thank you for you help !
![image](https://github.com/mpgn/CrackMapExec/assets/46540237/f9b94730-c98f-4415-8cee-303cc774120c)
