### ISSUE TITLE
RDP module - cannot access local variable 'wmi_rdp' where it is not associated with a value

### ISSUE THREAD

**Issue by bongobongoland** [mpgn/CrackMapExec#125]
<img width="1192" alt="2023-08-26_21-59" src="https://github.com/mpgn/CrackMapExec/assets/129246896/fd262ef2-06fa-42c3-9560-4f4eb587cddd">
<img width="740" alt="2023-08-26_22-06" src="https://github.com/mpgn/CrackMapExec/assets/129246896/1556b31e-981a-4ff2-b28d-0849e313a1ca">

[*] Windows 7 Professional 7601 Service Pack 1 x64
[-] Unexpected wmi error: DCOM SessionError: unknown error code: 0x800706ba
ERROR    Exception while calling proto_flow() on target 192.168.1.2: cannot access local variable 'wmi_rdp' where it is not associated with a value

**Comment by XiaoliChan** [comment]
so, please execute impacket wmiexec.py
```
wmiexec.py administrator:password@192.168.1.2 -debug
```

Not the `smb/wmiexec.py`

**Comment by bongobongoland** [comment]
<img width="1137" alt="2023-08-26_22-52" src="https://github.com/mpgn/CrackMapExec/assets/129246896/2331dfcf-1939-4e7f-9811-1f70e3245e3b">

**Comment by XiaoliChan** [comment]
Ha, I know what happened, this is another firewall issue, can you disable the firewall and try again?

**Comment by bongobongoland** [comment]
Yes, you are correct! I have manually disabled the firewall. Specifically, the Domain profile. And it works now.
If it's possible to disable the firewall using -x? If so, then it's another example why we need -x & modules chained.

**Comment by XiaoliChan** [comment]
> Yes, you are correct! I have manually disabled the firewall. Specifically, the Domain profile. And it works now. If it's possible to disable the firewall using -x? If so, then it's another example why we need -x & modules chained.

I add a new PR to avoid this ugly exception.

For `chains`, I still need to think about it.

**Comment by XiaoliChan** [comment]
BTW, issue #66 should be closed. (make issues clean up)

**Comment by NeffIsBack** [comment]
> BTW, issue #66 should be closed. (make issues clean up)

Go ahead :) you opened it
