### ISSUE TITLE
Wiki is down ⏬

### ISSUE THREAD

**Issue by n3rada** [mpgn/CrackMapExec#135]
The wiki seems totally down: https://www.crackmapexec.wiki/

![image](https://github.com/mpgn/CrackMapExec/assets/72791564/a03a63d8-fe34-48a4-a26e-63d6d7c72dcd)

**Comment by XiaoliChan** [comment]
https://wiki.porchetta.industries/getting-started/database-general-usage

**Comment by n3rada** [comment]
Do you have any information about this?

**Comment by NeffIsBack** [comment]
Mpgn is working on it. In the meantime just use wiki.porchetta.industries

**Comment by n3rada** [comment]
Was down too this morning btw

**Comment by NeffIsBack** [comment]
Huh okay weird, was working for me about 23h ago atleast

**Comment by XiaoliChan** [comment]
it works now

**Comment by XiaoliChan** [comment]
it works now
