### ISSUE TITLE
Ntlmrelayx and fqdn error

### ISSUE THREAD

**Issue by aleemladha** [mpgn/CrackMapExec#38]
Hi ,

I was using ntlmrelayx and bloodhound with an empty password 

I get an error while using the fqdn 

With the old version it works fine

**Comment by aleemladha** [comment]
![image](https://github.com/mpgn/CrackMapExec/assets/26311391/88c8a943-b0d1-4dba-83a1-432c04f28598)


updated version using ntlmrelayx

![image](https://github.com/mpgn/CrackMapExec/assets/26311391/5932cf63-e40a-47f2-9949-df53ca5f663b)

**Comment by mpgn** [comment]
@NeffIsBack I think we can go with a check if the password is empty there, and if empty, we don't check the fqdn https://github.com/mpgn/CrackMapExec/blob/master/cme/connection.py#L328

**Comment by aleemladha** [comment]
Hi , I have managed to solve it

line 328 : add before the “.” 

and self.password != “” and secret !=“”

**Comment by NeffIsBack** [comment]
> @NeffIsBack I think we can go with a check if the password is empty there, and if empty, we don't check the fqdn https://github.com/mpgn/CrackMapExec/blob/master/cme/connection.py#L328

LGTM:+1:

**Comment by Cyb3rC3lt** [comment]
Glad I saw this, it wasn't working for me at a client yesterday now I can see my notes use "-p none". I'll make sure to remove the dummy password in future 👍🏻. Does make me wonder should there be a log of these little required changes per release....
