### ISSUE TITLE
id creds fail

### ISSUE THREAD

**Issue by Unreachabl** [mpgn/CrackMapExec#45]
**Describe the bug**
When calling creds id from the database, the error "IndexError: list index out of range" appears.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: ` poetry run crackmapexec smb 10.10.10.10 -id 8`
Resulted in:
```
ERROR    Exception while calling proto_flow() on target 10.10.10.10: list index out of range  

...
```

**Expected behavior**
will be logged in using the accounting data from the database

**Screenshots**
![Shot 0001](https://github.com/mpgn/CrackMapExec/assets/139502727/7c19798f-6cd4-4b8a-927b-f0bc10444658)

**Crackmapexec info**
 - OS: Linux kali 6.3.0-kali1-amd64
 - Version of CME 6.0.0
 - Installed from: github

**Comment by NeffIsBack** [comment]
Thanks for the bug report!
This should be fixed in PR #49. If you want to test it pull down and checkout the branch :)
