### ISSUE TITLE
macos fails to run

### ISSUE THREAD

**Issue by JackeyLov5** [mpgn/CrackMapExec#52]
➜ ./cme
env: python: No such file or directory

macos has removed python2, that is, python, in previous versions
I installed python3 with brew. Maybe there is a conflict in the python name? Thanks🙏

**Comment by JackeyLov5** [comment]
I'm sorry that I didn't figure it out, but why not use python3.11 to execute it? My own system's 3.9.6 doesn't work. Thank you for your answer.

**Comment by JackeyLov5** [comment]
Sorry for my question, but I still hope you can support me Thank you

**Comment by mpgn** [comment]
Hello, download the version on need on this page: [https://github.com/mpgn/CrackMapExec/actions/runs/5444142064 or](https://github.com/mpgn/CrackMapExec/releases/tag/v6.0.1)

**Comment by JackeyLov5** [comment]
Thank you for not thinking out a new binary, sorry to bother you

**Comment by NeffIsBack** [comment]
Is it working with the new binary?

**Comment by mpgn** [comment]
no info, closing, feel free to reopen :)
