### ISSUE TITLE
SMB Shares - Download Files [Bug]

### ISSUE THREAD

**Issue by godylockz** [mpgn/CrackMapExec#54]
**Describe the bug**
The SMB downloader of crackmapexec does not return a error code when failing execution, the expected file is also written to disc with 0 bytes even though the download failed.

```sh
$ cme smb authority.htb --share Development --get-file 'Automation/Ansible/LDAP/meta/main.yml' 'main.yml'
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [*] Copying Automation/Ansible/LDAP/meta/main.yml to main.yml
SMB         authority.htb   445    AUTHORITY        [-] Error reading file Development: SMB SessionError: STATUS_USER_SESSION_DELETED(The remote user session has been deleted.)
$ echo $?
0
```

Also finding inconsistencies between guest/null usernames. Shouldn't all of these cases be tried if no credential/guest/empty username:
SMB Client:
```sh
$ smbclient --no-pass -L //authority.htb

	Sharename       Type      Comment
	---------       ----      -------
	ADMIN$          Disk      Remote Admin
	C$              Disk      Default share
	Department Shares Disk      
	Development     Disk      
	IPC$            IPC       Remote IPC
	NETLOGON        Disk      Logon server share 
	SYSVOL          Disk      Logon server share 
$ smbclient -U 'guest%' -L //authority.htb          

	Sharename       Type      Comment
	---------       ----      -------
	ADMIN$          Disk      Remote Admin
	C$              Disk      Default share
	Department Shares Disk      
	Development     Disk      
	IPC$            IPC       Remote IPC
	NETLOGON        Disk      Logon server share 
	SYSVOL          Disk      Logon server share 
```
CME:
```sh
$ cme smb authority.htb -u 'guest' --shares
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [-] Error enumerating shares: STATUS_USER_SESSION_DELETED

$ cme smb authority.htb -u 'guest' -p '' --shares
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [+] authority.htb\guest:
SMB         authority.htb   445    AUTHORITY        [*] Enumerated shares
SMB         authority.htb   445    AUTHORITY        Share           Permissions     Remark
SMB         authority.htb   445    AUTHORITY        -----           -----------     ------
SMB         authority.htb   445    AUTHORITY        ADMIN$                          Remote Admin
SMB         authority.htb   445    AUTHORITY        C$                              Default share
SMB         authority.htb   445    AUTHORITY        Department Shares
SMB         authority.htb   445    AUTHORITY        Development     READ
SMB         authority.htb   445    AUTHORITY        IPC$            READ            Remote IPC
SMB         authority.htb   445    AUTHORITY        NETLOGON                        Logon server share
SMB         authority.htb   445    AUTHORITY        SYSVOL                          Logon server share

$ cme smb authority.htb -u '' -p '' --shares
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [+] authority.htb\:
SMB         authority.htb   445    AUTHORITY        [-] Error enumerating shares: STATUS_ACCESS_DENIED

$ cme smb authority.htb --shares
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [-] Error enumerating shares: STATUS_USER_SESSION_DELETED
```

**Questions:**
Is there a way to download multiple files in one go?

**Crackmapexec info**
 - OS: Kali 
 - Version of CME: 6.0.1,
 - Installed from: pipx

**Comment by mpgn** [comment]
Hello

`smbclient --no-pass -L //authority.htb` is the same as `smbclient -U 'guest%' -L //authority.htb` which is the same as `cme smb authority.htb -u 'guest' -p '' --shares``

The result on cme are the same as smbclient as excepted

**Comment by NeffIsBack** [comment]
Also i am not sure if deleting the file in case of an error brings an advantage. For example if the connection closes during the extraction there still might be valuable information in the semi-downloaded file.

To your question: 
No, it is not possible to download multiple files at once, yet. 
Contributions are welcome :D

**Comment by godylockz** [comment]
Hey thanks guys! Just added a fix/improvements to spider_plus!

One thing that drives me crazy is when i mistype the domain name of the target. I didn't want to add it to the pull request to spider_plus. Do you think its worth changing ?
Line 67 `self.logger.info(f"Error resolving hostname {self.hostname}: {e}")`  in `cme/connection.py` to `self.logger.display` ...?

Also if the target doesn't have SMB or whatever service you are doing, would it be possible to at-least notify the user. My idea is that if you are enumerating multiple targets, `logger.debug` / `logger.info`, for single targets `logger.display`. I tried to pinpoint exactly where this is happening but couldn't exactly find where that would go...

**Comment by NeffIsBack** [comment]
Can you give me the output difference? I wonder why `.info` even exists anymore, if i am not missing something everything should be `.display` not but i still see a lot of `.info` across cme.

To the second point, this was argued about a lot in the past :D The line where a connection is established is https://github.com/mpgn/CrackMapExec/blob/35d2619cfb812dd08bffc4597cf6f2278762bc6d/cme/connection.py#L127

**Comment by mpgn** [comment]
`.info` -> --verbose ;)

**Comment by NeffIsBack** [comment]
Huh that sounds complicated. What are you trying to achieve? 
If you just want to add info logging when an connection can't be established you could simply add an else to the `if self.create_conn_obj()` and log that

**Comment by godylockz** [comment]
> Huh that sounds complicated. What are you trying to achieve? If you just want to add info logging when an connection can't be established you could simply add an else to the `if self.create_conn_obj()` and log that

```sh
$ cme smb authority.htb --share Development --get-file 'Automation/Ansible/LDAP/meta/main.yml' 'main.yml'
SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
SMB         authority.htb   445    AUTHORITY        [*] Copying Automation/Ansible/LDAP/meta/main.yml to main.yml
SMB         authority.htb   445    AUTHORITY        [-] Error reading file Development: SMB SessionError: STATUS_USER_SESSION_DELETED(The remote user session has been deleted.)
$ echo $?
0
```

Trying to make the exit code not 0 since crackmapexec failed. It did not crash, but provided a failure.

So say you wanted to do a wrapper around this command ? You couldn't figure out it failed right now just by the exit code alone. You would have to do a output-text parsing on `[-]` for instance.

**Comment by godylockz** [comment]
> Can you give me the output difference? I wonder why `.info` even exists anymore, if i am not missing something everything should be `.display` not but i still see a lot of `.info` across cme.
> 
> To the second point, this was argued about a lot in the past :D The line where a connection is established is
> 
> https://github.com/mpgn/CrackMapExec/blob/35d2619cfb812dd08bffc4597cf6f2278762bc6d/cme/connection.py#L127

Normal:
![image](https://github.com/mpgn/CrackMapExec/assets/81207744/3ae5c8d0-ef7c-46ae-8117-6e42bff589d9)

Verbose:
![image](https://github.com/mpgn/CrackMapExec/assets/81207744/b245d72c-19ef-4671-a36b-3c267384eba5)

**Comment by NeffIsBack** [comment]
> > Huh that sounds complicated. What are you trying to achieve? If you just want to add info logging when an connection can't be established you could simply add an else to the `if self.create_conn_obj()` and log that
> 
> ```shell
> $ cme smb authority.htb --share Development --get-file 'Automation/Ansible/LDAP/meta/main.yml' 'main.yml'
> SMB         authority.htb   445    AUTHORITY        [*] Windows 10.0 Build 17763 x64 (name:AUTHORITY) (domain:authority.htb) (signing:True) (SMBv1:False)
> SMB         authority.htb   445    AUTHORITY        [*] Copying Automation/Ansible/LDAP/meta/main.yml to main.yml
> SMB         authority.htb   445    AUTHORITY        [-] Error reading file Development: SMB SessionError: STATUS_USER_SESSION_DELETED(The remote user session has been deleted.)
> $ echo $?
> 0
> ```
> 
> Trying to make the exit code not 0 since crackmapexec failed. It did not crash, but provided a failure.
> 
> So say you wanted to do a wrapper around this command ? You couldn't figure out it failed right now just by the exit code alone. You would have to do a output-text parsing on `[-]` for instance.

Wrapper? As it is already in an if clause you could simply use `else` to catch if no connection could be established (aka no smb open). As for the exit code, yes there is not an implementation for exit codes as cme is not really designed to be used inside scripts for example. Not sure how you would do that properly

**Comment by NeffIsBack** [comment]
> After (https://github.com/mpgn/CrackMapExec/pull/55)
> Verbose:

That looks nice 👍

**Comment by mpgn** [comment]
Should we close the issue or not ?
