### ISSUE TITLE
RDP Module needs to be improved

### ISSUE THREAD

**Issue by bongobongoland** [mpgn/CrackMapExec#66]
Hey peeps!

The RDP module is a bit useless because it doesn't update the firewall settings!! This can be done by quickly running
`netsh firewall set service type = remotedesktop mode = enable`
or
`netsh advfirewall firewall add rule name="RDP" protocol=TCP dir=in localport=3389 action=allow`

Another thing, it would be useful to know the port. So, if CME could simly run
`REG QUERY "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber` 
(and then convert it to decimals) and print out the result in the window, it would make the module even lovelier :)

Cheers!

**Comment by XiaoliChan** [comment]
Using wmi to configure rdp is a good choice.

**Comment by XiaoliChan** [comment]
I will try to rewrite this module

**Comment by bongobongoland** [comment]
Well. The algorithm should be as follows: 

1) check the port.

2) check if TermService is running.

2.1) If it's already running, then check or/and edit firewall rules. And print RDP @ 3389 is already running.
2.2) If not running, then start TermService and print what needs to be printed and the port, of course.

Now, occasionally, TermService is acting up and needs a restart. So maybe instead of starting a restart is a better option.

**Comment by XiaoliChan** [comment]
> Well. The algorithm should be as follows:
> 
> 1. check the port.
> 2. check if TermService is running.
> 
> 2.1) If it's already running, then check or/and edit firewall rules. And print RDP @ 3389 is already running. 2.2) If not running, then start TermService and print what needs to be printed and the port, of course.
> 
> Now, occasionally, TermService is acting up and needs a restart. So maybe instead of starting a restart is a better option.

Sure, I have already done these, you can try `rdp` module in `wmiexec-pro`, I will port it to CME later.

**Comment by XiaoliChan** [comment]
@bongobongoland It this what you want?
![image](https://github.com/mpgn/CrackMapExec/assets/30458572/7f28b0fd-066c-4b88-b08d-57c9f99310d1)

**Comment by bongobongoland** [comment]
Looks good!

**Comment by bongobongoland** [comment]
How do you enable ram? 
```
New-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Lsa" -Name "DisableRestrictedAdmin" -Value "0" -PropertyType DWORD -Force
```
?

**Comment by XiaoliChan** [comment]
> How do you enable ram?
 wmi stdregprov

**Comment by bongobongoland** [comment]
That's good. I think it's more discreet and quieter than regedit/ps. But I could be wrong.

**Comment by bongobongoland** [comment]
After numerous tests I can confirm that in its current state the module doesn't work anywhere :) 
Because of the firewall, as mentioned earlier.

**Comment by XiaoliChan** [comment]
> After numerous tests I can confirm that in its current state the module doesn't work anywhere :)
> Because of the firewall, as mentioned earlier.

yes, so I will add a option allow users to choice what method they want to use.

**Comment by XiaoliChan** [comment]
@bongobongoland this issue should be close now :)
