### ISSUE TITLE
Broken Pipe Error while attempting to login will create a false positive

### ISSUE THREAD

**Issue by dinosn** [mpgn/CrackMapExec#73]
Whilst testing multiple systems systems, an error of "Broken Pipe Error while attempting to login" will create a false positive directly after, showing a positive [+] mark for the host.

**To Reproduce**
Steps to reproduce the behavior i.e.:
Command: `crackmapexec smb hosts.txt -u username -p password`
Resulted in:

```
SMB         xx.xx.xx.10     445    WSSYSTEM1  [-] Broken Pipe Error while attempting to login
SMB         xx.xx.xx.10     445    WSSYSTEM1  [+] WSSYSTEM1\Administrator:password 
...
```

What is expected upon the case is to have a [-]  response as the login process did not complete.

**Crackmapexec info**
 - OS: Ubuntu
 - Version of CME 6.0.1
 - Installed from: poetry with latest repo pull from this env.

Regards,
Nicolas

**Comment by mpgn** [comment]
Hello,

Can you run the command `crackmapexec --debug smb hosts.txt -u username -p password` and past the output ?

**Comment by mpgn** [comment]
Should be fixed
