### ISSUE TITLE
Bug in the ADCS Enumeration

### ISSUE THREAD

**Issue by dreizehnutters** [mpgn/CrackMapExec#8]
**Describe the bug**
The ADCS module fails use the correct baseDN in its ldap searches.

**To Reproduce**
Testbench used: https://tryhackme.com/room/adcertificatetemplates
Command: `crackmapexec ldap $IP -u thm -p 'Password1@' -M ADCS --port 636`
Resulted in:
```
SMB         10.10.199.118   445    LUNDC            [*] Windows 10.0 Build 17763 x64 (name:LUNDC) (domain:lunar.eruca.com) (signing:True) (SMBv1:False)
LDAP        10.10.199.118   636    LUNDC            [+] lunar.eruca.com\thm:Password1@ (Pwn3d!)
ADCS        10.10.199.118   636    LUNDC            [*] Starting LDAP search with search filter '(objectClass=pKIEnrollmentService)'
ADCS        10.10.199.118   636    LUNDC            [-] Obtained unexpected exception: Error in searchRequest -> referral: 0000202B: RefErr: DSID-03100835, data 0, 1 access points
    ref 1: 'eruca.com'
```

**Expected behavior**
Module should handle edge case

**Crackmapexec info**
 - OS: Kali
 - Version of CME 6.0
 - Installed from: pipx

**Comment by dreizehnutters** [comment]
the bug seems to located within the baseDN calculation

![image](https://github.com/mpgn/CrackMapExec/assets/7869385/ef889e9e-7ace-46fa-813e-e8c5fe8d58f9)


![image](https://github.com/mpgn/CrackMapExec/assets/7869385/7617c134-2f04-4210-9491-d98f6e2ddeb5)

**Comment by NeffIsBack** [comment]
Pull Requests are very welcome, if you manage to solve the problem on your own :)

**Comment by dreizehnutters** [comment]
I mean I can solve it, but I dont know what else might break ? i think the baseDN transformation was done on purpose ?

**Comment by NeffIsBack** [comment]
If you find a solution to your problem open up a PR. We will test it and take a look into it to check if it breaks something 👍

**Comment by dreizehnutters** [comment]
PR is commited.
If I find the time I also plan to add ESC1 detection...(not sure if we need another ADCS enumeration tool ;)

**Comment by mpgn** [comment]
Shoud be fixed :)
