### ISSUE TITLE
Improve colors

### ISSUE THREAD

**Issue by ShutdownRepo** [mpgn/CrackMapExec#92]
For a while now, [Exegol](exegol.rtfd.io) has been colorizing CrackMapExec's output with [grc](https://github.com/garabik/grc) in order to improve ease of life and spot misconfigurations way easier and faster.

The following colors were applied:
- Signing True: `signing:True` in `bold green`
- Signing False: `signing:False` in `bold red`
- SMB1 True: `SMBv1:True` in `yellow`
- SMB1 False: `SMBv1:True` in `blue`

Now that CME uses rich, we can't use grc anymore since all previous colors would be stripped, and we don't want that.
In order to get back base CME colors, we removed our colorization and intended on opening a PR where we would add the colors directly in CME (https://github.com/ThePorgs/Exegol-images/issues/202).

At the time we used grc to set up custom colors, we couldn't, because of CME's logging discrepancies (https://github.com/Porchetta-Industries/CrackMapExec/issues/534)

I tried again and probably don't know the code well enough to do it, I think the logging discrepancies I raised are still here.

Any way CME could add those colors to these essential information that don't usually stand out if we're working with lots of machines?

**Comment by NeffIsBack** [comment]
This sounds like a cool feature to me. I will open up a PR where we can discuss how exactly that will look like

**Comment by mpgn** [comment]
Something like this

![image](https://github.com/mpgn/CrackMapExec/assets/5891788/be7ffac1-6ec3-4e23-a136-8700df2def09)

**Comment by NeffIsBack** [comment]
@ShutdownRepo opened up a PR, please check it out if that's what you are looking for

**Comment by mpgn** [comment]
![image](https://github.com/mpgn/CrackMapExec/assets/5891788/a4f9d55d-83ff-412d-8d21-0dc8a63f3402)

**Comment by ShutdownRepo** [comment]
That was fast and effective! 🫡
Thank you!
