### ISSUE TITLE
[Feature Request] Allow switching core when using RDP

### ISSUE THREAD

**Issue by XiaoliChan** [mpgn/CrackMapExec#94]
As you can see, aardwolf is not pretty much stable, sometimes using `xfreerdp` is much better.

So, adding `--core` argument allows users to switch core between `["aardwolf", "xfreerdp"]`

Notes:
- `xfreerdp` does not allow headless, which means screenshot & ducky script is not working.

Demo:
- [cme-xfreerdp](https://github.com/XiaoliChan/CrackMapExec-Extension/tree/main/cme-xfreerdp)
- `Kerberos Auth` not working in this demo.

References:
- [RDPassSpray](https://github.com/xFreed0m/RDPassSpray)

**Comment by mpgn** [comment]
Hello,

popen inside cme is not something I not prepared to do :)
